version: "2"
services:
  line-art-automatic-coloring-server:
    #image: "LineArtAutomaticColoring-Server:latest" #這個會嘗試去docker hub取得image檔，取得失敗則會報錯，不會去抓local image檔
    build: . #直接使用Dockerfile build專案來建立要使用的image檔，不可與image共存
    container_name: service
    ports:
      - "8083:80"
      - "4434:443"
    volumes:
      - "/home/jack/Documents/LineArtAutomaticColoring-server/flaskr/checkpoint:/app/flaskr/checkpoint"
      - "/home/jack/Documents/LineArtAutomaticColoring-server/logs/:/app/logs"
    restart: always